### ISSUE TITLE
npm install  error

### ISSUE THREAD

**Issue by sureface** [BootstrapDash/purple-react-free#3]
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'E:\\Purple-React\\template\\demo_1\\node_modules\\browser-resolve',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'E:\Purple-React\template\demo_1\node_modules\browser-resolve\node_modules'] 
{
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'E:\\Purple-React\\template\\demo_1\\node_modules\\browser-resolve\\node_modules'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path E:\Purple-React\template\demo_1\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe E:\Purple-React\template\demo_1\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --li
bsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'E:\\Purple-React\\template\\demo_1\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.17.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\Purple-React\template\demo_1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (E:\Purple-React\template\demo_1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (E:\Purple-React\template\demo_1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at E:\Purple-React\template\demo_1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at E:\Purple-React\template\demo_1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at E:\Purple-React\template\demo_1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:210:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\Purple-React\template\demo_1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (E:\Purple-React\template\demo_1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (E:\Purple-React\template\demo_1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at E:\Purple-React\template\demo_1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at E:\Purple-React\template\demo_1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at E:\Purple-React\template\demo_1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:210:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\Purple-React\template\demo_1\node_modules\which\which.js:13:12)
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (E:\Purple-React\template\demo_1\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (E:\Purple-React\template\demo_1\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (E:\Purple-React\template\demo_1\node_modules\graceful-fs\polyfills.js:295:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:210:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Purple-React\\template\\demo_1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd E:\Purple-React\template\demo_1\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.17.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: C:\Users\hp\AppData\Local\npm-cache\_logs\2023-09-20T09_17_13_462Z-debug-0.log

## How can i fix this ?

**Comment by gul-cincik** [comment]
It seems like you're facing issues with setting up the Node.js environment for your project. 

1. Install Node Version Manager (nvm):
Follow the guide at [](https://www.freecodecamp.org/news/node-version-manager-nvm-install-guide/) to install nvm.

2. Install Node.js v14:
Once nvm is installed, run the following commands in your command prompt:

`nvm install 14`
`nvm use 14`

3. Install npm packages:
After setting up Node.js v14, you can proceed with running the `npm install` command to install the necessary packages for your project.
